#!/bin/bash
# selector menu
# Author: Franck Jouvanceau

# Icons for -o filenames, can be overriden using env variables to fit terminal font
: "${SELECTOR_FOLDER_ICON:=}" # 🖿 🗀 📁 📂 🖿        
: "${SELECTOR_FILE_ICON:=}" #  🗎            🗋 🖹   📄
: "${SELECTOR_CASEI:=false}"
: "${SELECTOR_POWERLINE:=y}"
: "${SELECTOR_COL_PROMPT:=30;90;180}" # blue
: "${SELECTOR_COL_TEXT:=255;255;255}" # white
: "${SELECTOR_COL_TOTAL:=32;64;64}"   # darkggrey
: "${SELECTOR_COL_NUM:=36;114;67}"    # green
: "${SELECTOR_COL_ARROW:=41;98;114}"  # cyan
: "${SELECTOR_COL_ITEM:=118;141;255}" # light blue
: "${SELECTOR_COL_SELECTED:=42;221;244}" # light cyan
: "${SELECTOR_COL_COMMENT:=168;110;2}" #
: "${SELECTOR_COL_COMSEL:=222;203;49}" #
: "${SELECTOR_USE_TPUT:=false}"        # use ansi

$SELECTOR_USE_TPUT && alias _tput=tput
type gnustty >/dev/null 2>&1 && _sel_stty='gnustty' || _sel_stty='stty'

_tput() {
    case "$1" in
        # -------- Erase eol/eos ----------
        el)  printf '\e[K' ;;
        ed)    printf '\e[J' ;;
        # -------- Cursor movement --------
        cuu) printf '\e[%dA' "${2:-1}" ;;
        cud) printf '\e[%dB' "${2:-1}" ;;
        cuu1) printf '\e[1A' ;;
        cud1) printf '\e[1B' ;;
        cuf) printf '\e[%dC' "${2:-1}" ;;
        cub) printf '\e[%dD' "${2:-1}" ;;
        cuf1) printf '\e[1C' ;;
        cub1) printf '\e[1D' ;;
        # -------- Cursor visibility --------
        civis) printf '\e[?25l' ;;
        cnorm) printf '\e[?25h' ;;
        # -------- tty size -----------------
        lines)
            [ ! "$LINES" ] && LINES=$($_sel_stty size </dev/tty) && LINES=${LINES% *}
            printf '%s\n' "${LINES:-24}"
            ;;
        cols)
            [ ! "$COLUMNS" ] && COLUMNS=$($_sel_stty size </dev/tty) && COLUMNS=${COLUMNS#* }
            printf '%s\n' "${COLUMNS:-80}"
            ;;
        *)  tput "$@" ;;
    esac
}


# split _items lines to index 1 array _aitems
type mapfile >/dev/null 2>&1 && _items2array() { _aitems=(); mapfile -t -O 1 _aitems <<<"$_items"; } || {
  [ "$ZSH_VERSION" ] && _items2array() { set -A _aitems ${(f)_items}; } || _items2array() {
    # ksh/bash3
    typeset o="$IFS"
    IFS=$'\n'; set -f; _aitems=( _ $_items ); set +f; IFS="$o"
    unset '_aitems[0]'
  }
}

_menuprompt()
{
  typeset filt="${filter:-${_aitems[$_nsel]%%$'\t'*}}"
  printf "\r"
  printf "$disp_form" "$prompt" "$_nsel/$nbitems" "$filt"
  _tput el
  printf "\r"
}

_showmenu()
{
  typeset item icon fpath comment
  typeset -i i min max maxiw maxw maxcw lines w size

  _menuprompt
  lines=${_maxlines:-$LINES}
  ((lines >= LINES)) && ((lines=LINES-1))
  ((min=_nsel-lines+2))
  ((min <= 0)) && min=1
  ((max=min+lines-2))
  ((max > nbitems)) && max=$nbitems
  maxw=0
  for ((i=min;i<=max;i++))
  do
    item="${_aitems[$i]%%$'\t'*}"
    ((${#item} > maxw)) && maxw=${#item}
  done
  ((maxw+=2))
  w=${#nbitems}
  ((maxiw=COLUMNS-w-4))
  ((maxiw<0)) && maxiw=0
  ((maxcw=maxiw-maxw))
  ((maxcw<0)) && maxcw=0
  for ((i=min;i<=max;i++))
  do
    item="${_aitems[$i]}"
    comment=""
    [[ $item = *$'\t'* ]] && {
      comment="┆ ${item#*$'\t'}"
      item="${item%%$'\t'*}"
    }
    icon=''
    [ "$_sel_option" = filenames ] && {
      [[ "$item" = \~/* ]] && fpath="$HOME/"${item#\~/} || fpath="$item"
      if [ -d "$fpath" ] ;then icon="$SELECTOR_FOLDER_ICON "
      else [[ -e "$fpath" || -L "$fpath" ]] && icon="$SELECTOR_FILE_ICON ";fi
    }
    if ((_nsel == i)); then
      printf "$disp_item_sel" $w $i $maxw "$icon${item:0:$maxiw}" "${comment:0:$maxcw}"
    else
      printf "$disp_item" $w $i $maxw "$icon${item:0:$maxiw}" "${comment:0:$maxcw}"
    fi
    _tput el #clear end of line
  done
  size=$nbitems
  ((size >= lines)) && ((size=lines-1))
  # back to top of menu
  _tput ed
  _tput cuu $size
  printf "\r" # begin of line
}

_select()
{
  typeset newsel="$1"

  ((_nsel=newsel))
  ((_nsel <1 )) && _nsel=1
  ((_nsel >= nbitems)) && _nsel=$nbitems
  _showmenu
}

_items_split()
{
  typeset filt="$1" gopt=""
  [ "$SELECTOR_CASEI" = true ] && gopt="-i"
  [ "$filt" ] && {
    _nsel=''
    [ "$filt" = . ] && filt=''
    _items="$(\grep -F $gopt -- "$filt" 2>/dev/null <<<"$_items"|uniq)"
  }
  [ "$_nsel" ] && _items="${_aitems[$_nsel]}"
  _nsel=1
  _items2array
}

_readkey()
{
  typeset o=${1:-n} k tmout=0.001
  [ "$KSH_VERSION" ] && tmout=0.01
  IFS= read -rs"$o"1 key
  [ "$key" = $'\x1b' ] && key="" && while true
  do
    k=""
    LC_NUMERIC=C read -rs"$o"1 -t $tmout k 2>/dev/null # LC_NUMERIC=C for old ksh
    [ $? = 1 ] && [ "$BASH" ] && read -rs"$o"1 -t 1 k # old bash
    [ ! "$k" ] && key=${key:-$'\x1b'} && break
    key+="$k"
    case "$key" in
      '['[A-H]|'['*'~'|O[A-S]|'[1;2'[ABCDP-S]) break;;
    esac
  done
  #printf "%s" "$key"
}

_domenu()
{
  typeset o=n _force_nsel
  _nsel=''
  printf "\r"
  _tput el
  [ "$ZSH_VERSION" ] && o=k
  _items_split "$filter"
  [ "$_items" ] || return 1
  nbitems=${#_aitems[@]}
  [ "$nbitems" = 1 ] && {
    selected="${_aitems[1]}"
    return 0
  }
  _items_ori="$_items"
  _tput civis
  $_sel_stty -echo </dev/tty 2>/dev/null
  printf "\e[?7l" # nowrap
  : "${LINES:=$(_tput lines)}"
  : "${COLUMNS:=$(_tput cols)}"
  ((_maxlines > 2)) || _maxlines=''
  _showmenu
  while true
  do
    _readkey $o #$key
    [ "$_keyfunc" ] && { # custom key control
      $_keyfunc "$key" # 0: already managed / 1: managed exit / 2: default / 3: skip default
      case "$?" in
        0)
          _items_split "."
          filter=""
          nbitems=${#_aitems[@]}
          _select "${_force_nsel:-1}"
          _force_nsel=''
          continue;;
        1) break;;
        3) continue;;
      esac
    }
    case "$key" in
      '[A'|OA) #up
        filter='';_select "_nsel-1";;
      '[B'|OB) #down
        filter='';_select "_nsel+1";;
      '[H'|'[D'|OD|'[1;5H'|'[1;2D') #home or [shift] arrowleft
        filter='';_select "1";;
      '[F'|'[C'|OC|'[1;5F'|'[1;2C') #end or [shift] arrowright
        filter='';_select "nbitems";;
      '[6~'|$'\x06'|'[1;2B') #pagedn Ctl-F shift-down
        filter='';_select "_nsel+lines-1";;
      '[5~'|$'\x02'|'[1;2A') #pageup Ctl-B shift-up
        filter='';_select "_nsel-lines+1";;
      '[19~'|$'\x04'|'[3~') # F8 Ctl-D delete
        unset "_aitems[$_nsel]"
        [ "$ZSH_VERSION" ] && _aitems=("${(@)_aitems[1,$_nsel-1]}" "${(@)_aitems[$_nsel+1,$nbitems]}") ||\
          { _aitems=(_ "${_aitems[@]}") && unset '_aitems[0]'; }
        nbitems=${#_aitems[@]}
        _tput ed
        [ "$nbitems" = 0 ] && break
        filter='';_select "$_nsel";;
      $'\x7f'|$'\x08') #backspace
        filter="${filter%?}"
        _items="$_items_ori"
        _nsel=''
        _items_split "$filter"
        nbitems=${#_aitems[@]}
        [ "$_autofilter" = y ] && _showmenu || _menuprompt
        ;;
      $'\xf8') #meta (macos)
        break;;
      [[:graph:]]|" ") #text [a-zA-Z0-9/_?*\(\)\ .-])
        filter+="$key"
        [ "$_autofilter" = y ] && {
          _items_split "$filter"
          [ ! "$_items" ] && {
            printf "Not found !"
            _tput el
            read -rs"$o"1 -t 0.5 key 2>/dev/null
            _items="$_items_ori"
            filter="${filter%?}"
            _nsel=''
            _items_split "$filter"
          }
          nbitems=${#_aitems[@]}
          _showmenu
        }
        _menuprompt;;
      $'\x0c') # Ctl-L => refresh
        _showmenu;;
      $'\x01') # Ctl-A => all
        _maxlines=''
        _showmenu;;
      $'\x0d'|''|$'\n'|$'\t') # enter
        selected="${_aitems[$_nsel]}"
        break;;
      *) break;
    esac
  done
  printf "\e[?7h" #wrap
  _tput ed
  _tput cnorm
}

function selector
{
  typeset prompt filter
  typeset bg="\e[48;2;" fg="\e[38;2;" pl=""
  typeset wfg="$fg${SELECTOR_COL_TEXT}m"
  typeset _items _aitems _maxlines _autofilter _keyfunc _sel_option _nsel _items_ori disp_item_sel disp_item disp_form key nbitems
  prompt='select'
  selected=''
  _maxlines=''
  _autofilter=y
  _powerline="$SELECTOR_POWERLINE"
  _keyfunc=""
  _sel_option=""
  while [ $# -gt 0 ]; do
    case "$1" in
      -p|--prompt)
        [ "$2" ] && prompt="$2" || return 1
        ;;
      -i|--items)
        [ "$2" ] && _items="$2" || return 1
        ;;
      -f|--file)
        [ "$2" ] && _items="$(cat "$2")" || return 1
        ;;
      -m|--max)
        [ "$2" ] && _maxlines="$(($2+1))" || return 1
        ;;
      -P|--powerline)
        [ "$2" ] && _powerline="$2" || return 1
        ;;
      -F|--filter)
        [ "$#" -ge 2 ] && filter="$2" || return 1
        ;;
      -a|--autofilter)
        [ "$2" ] && _autofilter="$2" || return 1
        ;;
      -k|--keyfunc)
        [ "$2" ] && _keyfunc="$2" || return 1
        ;;
      -o|--option)
        [ "$2" ] && _sel_option="$2" || return 1
        ;;
      *)
        printf "usage: selector [-p <prompt>] -i <items>|-f <itemfile> [-P <y|n>] [-k <keyfunc>]\n"
        printf "args :\n"
        printf "%s\n" "  -p, --prompt          menu prompt"
        printf "%s\n" "  -i, --items           menu items \n separated [description \t separated]"
        printf "%s\n" "  -f, --file            file with items"
        printf "%s\n" "  -F, --filter          regexp pattern filter items"
        printf "%s\n" "  -P, --powerline       y or n, powerline symbol usage"
        printf "%s\n" "  -a, --autofilter      y or n, filter at keystrokes (default y)"
        printf "%s\n" "  -k, --keyfunc         Custom additional key function"
        return 1
        ;;
    esac
    shift 2
  done
  [ "$_powerline" = "y" ] || pl="►"
  [ "$_items" ] || return 1
  disp_item_sel="\n$bg${SELECTOR_COL_ARROW}m$wfg %*s $fg${SELECTOR_COL_ARROW}m\e[49m$pl$fg${SELECTOR_COL_SELECTED}m%-*s$fg${SELECTOR_COL_COMSEL}m%s\e[0m"
  disp_item="\n$fg${SELECTOR_COL_NUM}m %*s  $fg${SELECTOR_COL_ITEM}m%-*s$fg${SELECTOR_COL_COMMENT}m%s\e[0m"
  disp_form="$bg${SELECTOR_COL_PROMPT}m$wfg %s $fg${SELECTOR_COL_PROMPT}m$bg${SELECTOR_COL_TOTAL}m$pl$wfg %s$fg${SELECTOR_COL_TOTAL}m\e[49m$pl\e[0m %s"
  typeset _stty_ori=$($_sel_stty -g </dev/tty 2>/dev/null)
  $_sel_stty intr '' </dev/tty 2>/dev/null
  LC_ALL=$__selector_lc _domenu >&2
  $_sel_stty "$_stty_ori" </dev/tty 2>/dev/null
  selected="${selected%%$'\t'*}"
  [ "$selected" ] && printf "%s" "$selected" && return 0
  return 1
}

[[ "$LANG" = *UTF-8 ]] && __selector_lc="$LANG" || {
  type locale >/dev/null 2>/dev/null && locale -a |grep -iq "en_US.UTF-*8" && __selector_lc=en_US.UTF-8 || __selector_lc=C.UTF-8
}

[ "$1" ] && { selector "$@"; exit $?; }
:

